version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pwgio-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.23-alpine
    container_name: pwgio-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d